export type product = {
  id: number;
  title: string;
  image: string;
  images?: string[];
  price: number;
  color?: string[];
  discount?: string;
  rating?: number;
};

export const products: product[] = [
  {
    id: 1,
    title: "تیشرت زنانه کد 1737",
    image: "/fitland-shop/images/products/Rectangle 1167.png",
    price: 600000 ,
    color: ["334B4F", "515549", "F00000"],
    images: [
      "/fitland-shop/images/products/Rectangle 1167.png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    discount: "24%",
    rating: 5,
  },
  {
    id: 2,
    title: "تیشرت زنانه کد 1727",
    image: "/fitland-shop/images/products/Rectangle 1167 (1).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167.png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 190000,
    color: ["737989", "716C59", "FE9AA0"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 3,
    title: "تیشرت زنانه کد 1717",
    image: "/fitland-shop/images/products/Rectangle 1167 (2).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167.png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 160000,
    discount: "24%",
    rating: 1,
  },
  {
    id: 4,
    title: "تیشرت زنانه کد 1717",
    image: "/fitland-shop/images/products/Rectangle 1167 (3).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167.png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 260000,
    color: ["925253", "716C59", "FE9AA0"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 5,
    title: "تیشرت زنانه کد 1757",
    image: "/fitland-shop/images/products/Rectangle 1167 (4).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
      "/fitland-shop/images/products/Rectangle 1167.png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
    ],
    price: 175000,
    color: ["F2F2F2", "716C59", "FE9AA0"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 6,
    title: "تیشرت زنانه کد 1767",
    image: "/fitland-shop/images/products/Rectangle 1167 (5).png",
    images: [
    "/fitland-shop/images/products/Rectangle 1167 (5).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 389000,
    color: ["B9C28F", "716C59", "334B4F"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 7,
    title: "تیشرت زنانه کد 1757",
    image: "/fitland-shop/images/products/Rectangle 1167 (6).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (6).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 723000,
    color: ["E7CBDD", "515549", "032340"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 8,
    title: "",
    image: "/fitland-shop/images/products/Rectangle 1167 (7).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (7).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 120000,
    discount: "24%",
    rating: 5,
  },
  {
    id: 9,
    title: "تیشرت زنانه کد 1797",
    image: "/fitland-shop/images/products/Rectangle 1167 (8).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (8).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 100000,
    color: ["F00000", "515549", "334B4F"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 10,
    title: "تیشرت زنانه کد 1778",
    image: "/fitland-shop/images/products/Rectangle 1167 (9).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (9).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 675000,
    color: ["733C5E", "515549", "3A5152"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 11,
    title: "تیشرت زنانه کد 1777",
    image: "/fitland-shop/images/products/Rectangle 1167 (3).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 278000,
    color: ["8B7767", "8B7767", "3A5152"],
    discount: "24%",
    rating: 2,
  },
  {
    id: 12,
    title: "تیشرت زنانه کد 1827",
    image: "/fitland-shop/images/products/Rectangle 1167 (10).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (10).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 671000,
    color: ["7F9893", "515549", "AD96C6"],
    discount: "24%",
    rating: 3,
  },
  {
    id: 13,
    title: "تیشرت زنانه کد 1817",
    image: "/fitland-shop/images/products/Rectangle 1167 (5).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (5).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 155000,
    color: ["F00000", "515549", "334B4F"],
    discount: "24%",
    rating: 5,
  },
  {
    id: 14,
    title: "تیشرت زنانه کد 1807",
    image: "/fitland-shop/images/products/Rectangle 1167 (7).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (7).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 371000,
    discount: "24%",
    rating: 3,
  },
  {
    id: 15,
    title: "تیشرت زنانه کد 1807",
    image: "/fitland-shop/images/products/Rectangle 1167 (9).png",
    images: [
      "/fitland-shop/images/products/Rectangle 1167 (9).png",
      "/fitland-shop/images/products/Rectangle 1167 (1).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (3).png",
      "/fitland-shop/images/products/Rectangle 1167 (2).png",
      "/fitland-shop/images/products/Rectangle 1167 (4).png",
    ],
    price: 555000,
    color: ["8B7767", "3A5152", "F15827"],
    discount: "24%",
    rating: 4,
  },
  {
    id: 16,
    title: "تیشرت زنانه کد 1807",
    image: "/fitland-shop/images/products/Rectangle 1167 (10).png",
    images: [

    ],
    price: 655000,
    color: ["F15827", "515549", "334B4F"],
    discount: "24%",
    rating: 2,
  },
];
